spring:
  rabbitmq:
    host: member.itdev.co.kr
    port: 5672
    username: devUser
    password: devPassword
    virtual-host: vhost01
server:
  port: 8081
custom:
    message: Hello, member-service-dev!
