spring:
  rabbitmq:
    host: order.itdev.co.kr
    port: 5672
    username: stUser
    password: stPassword
    virtual-host: vhost02
server:
  port: 9999
custom:
  message: Hello, order-service-st!
