spring:
  rabbitmq:
    host: order.itdev.co.kr
    port: 5672
    username: devUser
    password: devPassword
    virtual-host: vhost01
server:
  port: 9998
custom:
  message: Hello, order-service-dev!
